name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to project 1
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/simonv3/secret-api/projects/1"

      - name: Assign issues and pull requests with `bug` label to project 3
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          contains(github.event.issue.labels.*.name, 'needs: discussion') ||
          contains(github.event.pull_request.labels.*.name, 'needs: discussion')
        with:
          project: "https://github.com/simonv3/secret-api/projects/1"
          column_name: "Needs: Discussion"
