name: Unit tests
on: 
  push:
    branches:
      - main
  pull_request:

jobs:

  Unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install our packages
        run: yarn install

      - name: Run our tests
        run:  yarn test
